In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sql
from sqlalchemy import create_engine

In [2]:
df_crime = pd.read_csv('crime.csv', encoding= 'unicode_escape')
df_offense_codes = pd.read_csv('offense_codes.csv', encoding= 'unicode_escape')

In [3]:
df_crime.head(10)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182070945,619,Larceny,LARCENY ALL OTHERS,D14,808,NaN,2018-09-02 13:00:00,2018,9,Sunday,13,Part One,LINCOLN ST,42.357791,-71.139371,"(42.35779134, -71.13937053)"
1,I182070943,1402,Vandalism,VANDALISM,C11,347,NaN,2018-08-21 00:00:00,2018,8,Tuesday,0,Part Two,HECLA ST,42.306821,-71.060300,"(42.30682138, -71.06030035)"
2,I182070941,3410,Towed,TOWED MOTOR VEHICLE,D4,151,NaN,2018-09-03 19:27:00,2018,9,Monday,19,Part Three,CAZENOVE ST,42.346589,-71.072429,"(42.34658879, -71.07242943)"
3,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,NaN,2018-09-03 21:16:00,2018,9,Monday,21,Part Three,NEWCOMB ST,42.334182,-71.078664,"(42.33418175, -71.07866441)"
4,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,NaN,2018-09-03 21:05:00,2018,9,Monday,21,Part Three,DELHI ST,42.275365,-71.090361,"(42.27536542, -71.09036101)"
5,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,NaN,2018-09-03 21:09:00,2018,9,Monday,21,Part Three,TALBOT AVE,42.290196,-71.071590,"(42.29019621, -71.07159012)"
6,I182070933,724,Auto Theft,AUTO THEFT,B2,330,NaN,2018-09-03 21:25:00,2018,9,Monday,21,Part One,NORMANDY ST,42.306072,-71.082733,"(42.30607218, -71.08273260)"
7,I182070932,3301,Verbal Disputes,VERBAL DISPUTE,B2,584,NaN,2018-09-03 20:39:37,2018,9,Monday,20,Part Three,LAWN ST,42.327016,-71.105551,"(42.32701648, -71.10555088)"
8,I182070931,301,Robbery,ROBBERY - STREET,C6,177,NaN,2018-09-03 20:48:00,2018,9,Monday,20,Part One,MASSACHUSETTS AVE,42.331521,-71.070853,"(42.33152148, -71.07085307)"
9,I182070929,3301,Verbal Disputes,VERBAL DISPUTE,C11,364,NaN,2018-09-03 20:38:00,2018,9,Monday,20,Part Three,LESLIE ST,42.295147,-71.058608,"(42.29514664, -71.05860832)"

In [4]:
df_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319073 entries, 0 to 319072
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   INCIDENT_NUMBER      319073 non-null  object
 1   OFFENSE_CODE         319073 non-null  int64
 2   OFFENSE_CODE_GROUP   319073 non-null  object
 3   OFFENSE_DESCRIPTION  319073 non-null  object
 4   DISTRICT             317308 non-null  object
 5   REPORTING_AREA       319073 non-null  object
 6   SHOOTING             1019 non-null    object
 7   OCCURRED_ON_DATE     319073 non-null  object
 8   YEAR                 319073 non-null  int64
 9   MONTH                319073 non-null  int64
 10  DAY_OF_WEEK          319073 non-null  object
 11  HOUR                 319073 non-null  int64
 12  UCR_PART             318983 non-null  object
 13  STREET               308202 non-null  object
 14  Lat                  299074 non-null  float64
 15  Long                 299074 non-null  float64
 16  Location             319073 non-null  object
dtypes: float64(2), int64(4), object(11)
memory usage: 41.4+ MB

In [5]:
df_offense_codes

     CODE                                       NAME
0     612           LARCENY PURSE SNATCH - NO FORCE
1     613                        LARCENY SHOPLIFTING
2     615    LARCENY THEFT OF MV PARTS & ACCESSORIES
3    1731                                     INCEST
4    3111                  LICENSE PREMISE VIOLATION
..    ...                                        ...
571  1806  DRUGS - CLASS B TRAFFICKING OVER 18 GRAMS
572  1807  DRUGS - CLASS D TRAFFICKING OVER 50 GRAMS
573  1610    HUMAN TRAFFICKING - COMMERCIAL SEX ACTS
574  2010                              HOME INVASION
575  1620  HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE

[576 rows x 2 columns]

In [6]:
engine = create_engine('sqlite://', echo = False)


# export the dataframe as a table to the sqlite engine

df_crime.to_sql("crime", con = engine)
df_offense_codes.to_sql("offense_codes", con = engine)

576

In [7]:
# sample query

sql='''

Select * 
from crime
limit 10

''';

    
df_sql = pd.read_sql_query(sql, con = engine)
df_sql

,index,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,0,I182070945,619,Larceny,LARCENY ALL OTHERS,D14,808,None,2018-09-02 13:00:00,2018,9,Sunday,13,Part One,LINCOLN ST,42.357791,-71.139371,"(42.35779134, -71.13937053)"
1,1,I182070943,1402,Vandalism,VANDALISM,C11,347,None,2018-08-21 00:00:00,2018,8,Tuesday,0,Part Two,HECLA ST,42.306821,-71.060300,"(42.30682138, -71.06030035)"
2,2,I182070941,3410,Towed,TOWED MOTOR VEHICLE,D4,151,None,2018-09-03 19:27:00,2018,9,Monday,19,Part Three,CAZENOVE ST,42.346589,-71.072429,"(42.34658879, -71.07242943)"
3,3,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,None,2018-09-03 21:16:00,2018,9,Monday,21,Part Three,NEWCOMB ST,42.334182,-71.078664,"(42.33418175, -71.07866441)"
4,4,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,None,2018-09-03 21:05:00,2018,9,Monday,21,Part Three,DELHI ST,42.275365,-71.090361,"(42.27536542, -71.09036101)"
5,5,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,None,2018-09-03 21:09:00,2018,9,Monday,21,Part Three,TALBOT AVE,42.290196,-71.071590,"(42.29019621, -71.07159012)"
6,6,I182070933,724,Auto Theft,AUTO THEFT,B2,330,None,2018-09-03 21:25:00,2018,9,Monday,21,Part One,NORMANDY ST,42.306072,-71.082733,"(42.30607218, -71.08273260)"
7,7,I182070932,3301,Verbal Disputes,VERBAL DISPUTE,B2,584,None,2018-09-03 20:39:37,2018,9,Monday,20,Part Three,LAWN ST,42.327016,-71.105551,"(42.32701648, -71.10555088)"
8,8,I182070931,301,Robbery,ROBBERY - STREET,C6,177,None,2018-09-03 20:48:00,2018,9,Monday,20,Part One,MASSACHUSETTS AVE,42.331521,-71.070853,"(42.33152148, -71.07085307)"
9,9,I182070929,3301,Verbal Disputes,VERBAL DISPUTE,C11,364,None,2018-09-03 20:38:00,2018,9,Monday,20,Part Three,LESLIE ST,42.295147,-71.058608,"(42.29514664, -71.05860832)"

In [8]:
# sample query

sql='''

Select * 
from offense_codes
limit 10

''';

    
df_sql = pd.read_sql_query(sql, con = engine)
df_sql

   index  CODE                                        NAME
0      0   612            LARCENY PURSE SNATCH - NO FORCE
1      1   613                         LARCENY SHOPLIFTING
2      2   615     LARCENY THEFT OF MV PARTS & ACCESSORIES
3      3  1731                                      INCEST
4      4  3111                   LICENSE PREMISE VIOLATION
5      5  2646                 LIQUOR - DRINKING IN PUBLIC
6      6  2204                        LIQUOR LAW VIOLATION
7      7  3810  M/V ACCIDENT - INVOLVING ÊBICYCLE - INJURY
8      8  3801                        M/V ACCIDENT - OTHER
9      9  3807           M/V ACCIDENT - OTHER CITY VEHICLE

In [9]:
# query to show count of auto theft and towed by phase of day vs month 

sql='''

with data as
(Select *,
substr(OCCURRED_ON_DATE, 12) as time,
case 
when substr(OCCURRED_ON_DATE, 12) between '06:00:00' and '11:00:00' then 'Morning'
when substr(OCCURRED_ON_DATE, 12) between '11:01:00' and '17:00:00' then 'Noon'
when substr(OCCURRED_ON_DATE, 12) between '17:01:00' and '20:00:00' then 'Evening'
when substr(OCCURRED_ON_DATE, 12) between '20:01:00' and '23:59:00' then 'Night'
when substr(OCCURRED_ON_DATE, 12) between '00:00:00' and '05:59:00' then 'Night'
else 'Not Available'
end as phase_of_day
from crime)

select phase_of_day,
sum(case when month = 1 then 1 else 0 end) as Jan,
sum(case when month = 2 then 1 else 0 end) as Feb,
sum(case when month = 3 then 1 else 0 end) as Mar,
sum(case when month = 4 then 1 else 0 end) as Apr,
sum(case when month = 5 then 1 else 0 end) as May,
sum(case when month = 6 then 1 else 0 end) as Jun,
sum(case when month = 7 then 1 else 0 end) as Jul,
sum(case when month = 8 then 1 else 0 end) as Aug,
sum(case when month = 9 then 1 else 0 end) as Sep,
sum(case when month = 10 then 1 else 0 end) as Oct,
sum(case when month = 11 then 1 else 0 end) as Nov,
sum(case when month = 12 then 1 else 0 end) as Dec
from data
where OFFENSE_CODE_GROUP in ('Auto Theft', 'Towed')
group by phase_of_day



''';

    
df_sql = pd.read_sql_query(sql, con = engine)
df_sql

  phase_of_day  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
0      Evening  134  133  135  152  157  180  222  193  157  151  153  143
1      Morning  368  372  425  439  583  668  659  806  557  510  424  456
2        Night  269  283  296  294  339  397  424  477  328  327  323  296
3         Noon  281  258  295  277  334  390  395  462  362  289  263  302

In [10]:
## script to get full offence name per district which has maximum occurence in respective district

sql='''

with data as
(Select district, offense_code, count(1) as no_of_crime,
rank() over (partition by district order by count(1) desc) as rank
from crime
where district is not null
group by district, offense_code)

select distinct district, offense_code, name, no_of_crime
from data d
join offense_codes o on o.code = d.offense_code
where rank = 1
order by district

''';

    
df_sql = pd.read_sql_query(sql, con = engine)
df_sql

   district  offense_code                                   NAME  no_of_crime
0        A1           802               ASSAULT SIMPLE - BATTERY         2148
1        A1           802                      ASSAULT & BATTERY         2148
2       A15          3115                     INVESTIGATE PERSON          464
3        A7          3006          SICK/INJURED/MEDICAL - PERSON         1040
4        B2          3301                         VERBAL DISPUTE         3008
5        B3          3301                         VERBAL DISPUTE         2957
6       C11          3831  M/V - LEAVING SCENE - PROPERTY DAMAGE         2713
7        C6          3006          SICK/INJURED/MEDICAL - PERSON         1508
8       D14          3410                    TOWED MOTOR VEHICLE         1487
9        D4           613                    LARCENY SHOPLIFTING         3219
10       D4           613        LARCENY SHOPLIFTING $200 & OVER         3219
11      E13          3006          SICK/INJURED/MEDICAL - PERSON         1127
12      E18          3006          SICK/INJURED/MEDICAL - PERSON         1349
13       E5          3006          SICK/INJURED/MEDICAL - PERSON         1187

In [11]:
## add a column which contains date of last incidents that happened in respective district

sql='''

Select *,
lag(OCCURRED_ON_DATE) over (partition by DISTRICT order by OCCURRED_ON_DATE) as last_incident_on
from crime
where district is not null
order by district, OCCURRED_ON_DATE


''';

    
df_sql = pd.read_sql_query(sql, con = engine)
df_sql.head(50)

,index,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location,last_incident_on
0,303001,I152067251,1102,Fraud,FRAUD - FALSE PRETENSE / SCHEME,A1,93,None,2015-06-15 00:00:00,2015,6,Monday,0,Part Two,FANEUIL HALL SQ,42.360205,-71.056208,"(42.36020464, -71.05620816)",None
1,318629,I152049585,2906,Violations,VAL - OPERATING UNREG/UNINS CAR,A1,69,None,2015-06-15 01:02:00,2015,6,Monday,1,Part Two,BEACON ST,42.355644,-71.071681,"(42.35564426, -71.07168077)",2015-06-15 00:00:00
2,318612,I152049607,617,Larceny,LARCENY THEFT FROM BUILDING,A1,115,None,2015-06-15 02:12:00,2015,6,Monday,2,Part One,LINCOLN ST,42.352018,-71.058116,"(42.35201794, -71.05811581)",2015-06-15 01:02:00
3,318670,I152049507,3114,Investigate Property,INVESTIGATE PROPERTY,A1,70,None,2015-06-15 07:30:00,2015,6,Monday,7,Part Three,LOUISBURG SQ,42.358472,-71.068619,"(42.35847240, -71.06861909)",2015-06-15 02:12:00
4,318674,I152049501,3125,Warrant Arrests,WARRANT ARREST,A1,123,None,2015-06-15 08:00:00,2015,6,Monday,8,Part Three,WASHINGTON ST,42.349973,-71.063488,"(42.34997256, -71.06348817)",2015-06-15 07:30:00
5,318647,I152049548,3207,Property Found,PROPERTY - FOUND,A1,107,None,2015-06-15 08:20:00,2015,6,Monday,8,Part Three,FEDERAL ST,42.356133,-71.056635,"(42.35613296, -71.05663451)",2015-06-15 08:00:00
6,317040,I152051617,2007,Restraining Order Violations,VIOL. OF RESTRAINING ORDER W NO ARREST,A1,111,None,2015-06-15 10:00:00,2015,6,Monday,10,Part Two,BOYLSTON ST,NaN,NaN,"(0.00000000, 0.00000000)",2015-06-15 08:20:00
7,318655,I152049535,1402,Vandalism,VANDALISM,A1,111,None,2015-06-15 10:30:00,2015,6,Monday,10,Part Two,TREMONT ST,42.353110,-71.064323,"(42.35311007, -71.06432264)",2015-06-15 10:00:00
8,318658,I152049531,2647,Other,THREATS TO DO BODILY HARM,A1,119,None,2015-06-15 10:30:00,2015,6,Monday,10,Part Two,BOYLSTON ST,42.352418,-71.065255,"(42.35241815, -71.06525499)",2015-06-15 10:30:00
9,318656,I152049534,2610,Other,TRESPASSING,A1,117,None,2015-06-15 10:40:00,2015,6,Monday,10,Part Two,WASHINGTON ST,42.352135,-71.062668,"(42.35213476, -71.06266757)",2015-06-15 10:30:00
10,318657,I152049532,3410,Towed,TOWED MOTOR VEHICLE,A1,66,None,2015-06-15 11:00:00,2015,6,Monday,11,Part Three,PINCKNEY ST,42.358774,-71.071425,"(42.35877431, -71.07142509)",2015-06-15 10:40:00
11,318613,I152049605,3001,Medical Assistance,DEATH INVESTIGATION,A1,68,None,2015-06-15 11:02:00,2015,6,Monday,11,Part Three,BOWDOIN ST,42.360382,-71.062858,"(42.36038173, -71.06285769)",2015-06-15 11:00:00
12,312611,I152056644,619,Larceny,LARCENY ALL OTHERS,A1,94,None,2015-06-15 13:28:00,2015,6,Monday,13,Part One,STATE ST,42.359230,-71.054466,"(42.35923021, -71.05446590)",2015-06-15 11:02:00
13,318611,I152049609,3115,Investigate Person,INVESTIGATE PERSON,A1,123,None,2015-06-15 13:40:00,2015,6,Monday,13,Part Three,WASHINGTON ST,42.349973,-71.063488,"(42.34997256, -71.06348817)",2015-06-15 13:28:00
14,316551,I152052194,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,A1,123,None,2015-06-15 15:15:00,2015,6,Monday,15,Part Three,STUART ST,42.350867,-71.063060,"(42.35086724, -71.06305976)",2015-06-15 13:40:00
15,318564,I152049678,802,Simple Assault,ASSAULT SIMPLE - BATTERY,A1,113,None,2015-06-15 15:15:00,2015,6,Monday,15,Part Two,FINANCIAL CTR,NaN,NaN,"(0.00000000, 0.00000000)",2015-06-15 15:15:00
16,318443,I152049861,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,74,None,2015-06-15 15:45:00,2015,6,Monday,15,Part One,NEW CHARDON ST,42.362608,-71.061327,"(42.36260750, -71.06132725)",2015-06-15 15:15:00
17,318539,I152049715,3114,Investigate Property,INVESTIGATE PROPERTY,A1,70,None,2015-06-15 16:00:00,2015,6,Monday,16,Part Three,LOUISBURG SQ,42.358472,-71.068619,"(42.35847240, -71.06861909)",2015-06-15 15:45:00
18,318590,I152049639,3114,Investigate Property,INVESTIGATE PROPERTY,A1,70,None,2015-06-15 16:04:00,2015,6,Monday,16,Part Three,LOUISBURG SQ,42.358472,-71.068619,"(42.35847240, -71.06861909)",2015-06-15 16:00:00
19,318554,I152049696,1843,Drug Violation,DRUGS - POSS CLASS B - INTENT TO MFR DIST DISP,A1,117,None,2015-06-15 18:46:00,2015,6,Monday,18,Part Two,LAGRANGE ST,42.351657,-71.064257,"(42.35165733, -71.06425694)",2015-06-15 16:04:00
20,318531,I152049730,2403,Disorderly Conduct,DISTURBING THE PEACE,A1,954,None,2015-06-15 19:48:00,2015,6,Monday,19,Part Two,FULTON ST,42.362936,-71.052538,"(42.36293611, -71.05253795)",2015-06-15 18:46:00
21,318494,I152049774,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,A1,95,None,2015-06-15 20:39:00,2015,6,Monday,20,Part Three,E INDIA ROW,42.357948,-71.050822,"(42.35794791, -71.05082219)",2015-06-15 19:48:00
22,318497,I152049772,3410,Towed,TOWED MOTOR VEHICLE,A1,68,None,2015-06-15 21:47:00,2015,6,Monday,21,Part Three,JOY ST,42.360589,-71.065103,"(42.36058947, -71.06510340)",2015-06-15 20:39:00
23,318495,I152049773,3502,Missing Person Located,MISSING PERSON - LOCATED,A1,111,None,2015-06-15 22:15:00,2015,6,Monday,22,Part Three,TREMONT ST,42.354284,-71.063804,"(42.35428377, -71.06380404)",2015-06-15 21:47:00
24,318496,I152049773,3501,Missing Person Reported,MISSING PERSON,A1,111,None,2015-06-15 22:15:00,2015,6,Monday,22,Part Three,TREMONT ST,42.354284,-71.063804,"(42.35428377, -71.06380404)",2015-06-15 22:15:00
25,318484,I152049793,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,A1,67,None,2015-06-16 03:45:00,2015,6,Tuesday,3,Part Three,CAMBRIDGE ST,42.361110,-71.067414,"(42.36110964, -71.06741369)",2015-06-15 22:15:00
26,318483,I152049794,1402,Vandalism,VANDALISM,A1,84,None,2015-06-16 04:24:00,2015,6,Tuesday,4,Part Two,PRINCE ST,42.364754,-71.054695,"(42.36475392, -71.05469547)",2015-06-16 03:45:00
27,318474,I152049813,1843,Drug Violation,DRUGS - POSS CLASS B - INTENT TO MFR DIST DISP,A1,116,None,2015-06-16 08:57:00,2015,6,Tuesday,8,Part Two,HARRISON AVE,42.351717,-71.061184,"(42.35171679, -71.06118419)",2015-06-16 04:24:00
28,318447,I152049853,617,Larceny,LARCENY THEFT FROM BUILDING,A1,67,None,2015-06-16 10:00:00,2015,6,Tuesday,10,Part One,CAMBRIDGE ST,42.361123,-71.065774,"(42.36112329, -71.06577409)",2015-06-16 08:57:00
29,318468,I152049822,3410,Towed,TOWED MOTOR VEHICLE,A1,84,None,2015-06-16 10:20:00,2015,6,Tuesday,10,Part Three,HANOVER ST,42.364924,-71.053318,"(42.36492400, -71.05331772)",2015-06-16 10:00:00
30,318438,I152049866,1810,Drug Violation,DRUGS - SALE / MANUFACTURING,A1,111,None,2015-06-16 12:16:00,2015,6,Tuesday,12,Part Two,BOYLSTON ST,42.352329,-71.064103,"(42.35232905, -71.06410340)",2015-06-16 10:20:00
31,318439,I152049866,1815,Drug Violation,DRUGS - POSSESSION,A1,111,None,2015-06-16 12:16:00,2015,6,Tuesday,12,Part Two,BOYLSTON ST,42.352329,-71.064103,"(42.35232905, -71.06410340)",2015-06-16 12:16:00
32,318393,I152049928,613,Larceny,LARCENY SHOPLIFTING,A1,97,None,2015-06-16 15:54:00,2015,6,Tuesday,15,Part One,TREMONT ST,42.359072,-71.059730,"(42.35907171, -71.05973044)",2015-06-16 12:16:00
33,318351,I152049977,3125,Warrant Arrests,WARRANT ARREST,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:54:00
34,318886,I142017108-00,1841,Drug Violation,DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Two,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
35,318887,I142017108-00,1841,Drug Violation,DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Two,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
36,318888,I142017108-00,1842,Drug Violation,"DRUGS - POSS CLASS A - HEROIN, ETC.",A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Two,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
37,318889,I142017108-00,3125,Warrant Arrests,WARRANT ARREST,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
38,318890,I142017108-00,3125,Warrant Arrests,WARRANT ARREST,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
39,318938,I140056633-00,3125,Warrant Arrests,WARRANT ARREST,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
40,318939,I140056633-00,2910,Violations,VAL - OPERATING AFTER REV/SUSP.,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Two,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
41,318940,I140056633-00,3125,Warrant Arrests,WARRANT ARREST,A1,64,None,2015-06-16 15:55:00,2015,6,Tuesday,15,Part Three,FRUIT ST,42.362403,-71.069547,"(42.36240281, -71.06954652)",2015-06-16 15:55:00
42,317955,I152050491,613,Larceny,LARCENY SHOPLIFTING,A1,116,None,2015-06-16 15:56:00,2015,6,Tuesday,15,Part One,WASHINGTON ST,42.352729,-71.062563,"(42.35272948, -71.06256291)",2015-06-16 15:55:00
43,318253,I152050106,3202,Property Found,PROPERTY - LOST THEN LOCATED,A1,77,None,2015-06-16 16:00:00,2015,6,Tuesday,16,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)",2015-06-16 15:56:00
44,318388,I152049935,3201,Property Lost,PROPERTY - LOST,A1,111,None,2015-06-16 16:23:00,2015,6,Tuesday,16,Part Three,WASHINGTON ST,42.352135,-71.062668,"(42.35213476, -71.06266757)",2015-06-16 16:00:00
45,318290,I152050057,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,A1,76,None,2015-06-16 19:45:00,2015,6,Tuesday,19,Part Three,ANTHONY RIP VALENTI WAY,42.363986,-71.060472,"(42.36398584, -71.06047223)",2015-06-16 16:23:00
46,318310,I152050030,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,A1,128,None,2015-06-16 20:07:00,2015,6,Tuesday,20,Part Three,ISABELLA ST,42.348735,-71.070492,"(42.34873541, -71.07049185)",2015-06-16 19:45:00
47,318304,I152050039,3109,Police Service Incidents,SERVICE TO OTHER PD INSIDE OF MA.,A1,112,None,2015-06-16 21:22:00,2015,6,Tuesday,21,Part Three,WASHINGTON ST,42.352729,-71.062563,"(42.35272948, -71.06256291)",2015-06-16 20:07:00
48,318300,I152050044,802,Simple Assault,ASSAULT SIMPLE - BATTERY,A1,72,None,2015-06-16 21:29:00,2015,6,Tuesday,21,Part Two,BOWDOIN ST,42.361180,-71.062864,"(42.36118028, -71.06286446)",2015-06-16 21:22:00
49,318285,I152050063,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,A1,161,None,2015-06-16 23:32:00,2015,6,Tuesday,23,Part Three,MARGINAL RD,42.347671,-71.065708,"(42.34767084, -71.06570791)",2015-06-16 21:29:00